// Package httputil — generic HTTP helper utilities.
//
// TLS helpers are split across two packages:
//
//   - internal/httputil (this file): protocol-level helpers and file-loading
//     helpers that apply to all TLS listeners and clients:
//     MinTLSVersion, NewServerTLSConfig, NewClientTLSConfig,
//     ConfigureTLSTrustEnvironment, LoadGatewayTLS.
//
//   - internal/proxy: certificate *generation* (GenerateSelfSignedTLS) lives
//     there because it is only needed when the proxy runs in self-signed mode.
//     It calls httputil.NewServerTLSConfig to assemble the final *tls.Config.
package httputil

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"os"
	"strings"

	"github.com/github/gh-aw-mcpg/internal/logger"
)

var logTLS = logger.ForFile()

// MinTLSVersion is the minimum TLS version enforced across all gateway listeners
// and clients. Centralizing this constant ensures a single point of change if
// the policy is tightened (e.g., to tls.VersionTLS13).
const MinTLSVersion = tls.VersionTLS12

// tlsTrustEnvKeys is the canonical set of well-known environment variables
// that point HTTP/TLS clients (Node.js, curl, git, Python requests) to a CA
// bundle.
var tlsTrustEnvKeys = []string{
	"NODE_EXTRA_CA_CERTS",
	"SSL_CERT_FILE",
	"GIT_SSL_CAINFO",
	"CURL_CA_BUNDLE",
	"REQUESTS_CA_BUNDLE",
}

// TLSTrustEnvKeys returns the set of trust-environment variable names used by
// ConfigureTLSTrustEnvironment.
//
// The returned slice is a defensive copy and can be safely modified by callers
// without affecting package behavior.
func TLSTrustEnvKeys() []string {
	return append([]string(nil), tlsTrustEnvKeys...)
}

// NewServerTLSConfig returns a *tls.Config for TLS server listeners carrying
// the provided certificate and the gateway-wide minimum TLS version.
func NewServerTLSConfig(cert tls.Certificate) *tls.Config {
	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   MinTLSVersion,
	}
}

// NewClientTLSConfig returns a *tls.Config suitable for outbound HTTP clients,
// enforcing the gateway-wide minimum TLS version.
func NewClientTLSConfig() *tls.Config {
	return &tls.Config{MinVersion: MinTLSVersion}
}

// ConfigureTLSTrustEnvironment sets all trust-environment variables to
// caCertPath so that
// child processes (Node.js, curl, git, Python) automatically trust the
// self-signed CA certificate generated by internal/proxy.GenerateSelfSignedTLS.
func ConfigureTLSTrustEnvironment(caCertPath string) error {
	if strings.ContainsAny(caCertPath, "\r\n") {
		return fmt.Errorf("invalid TLS CA cert path contains newline")
	}

	logTLS.Printf("Configuring TLS trust environment: caCertPath=%s, envVars=%v", caCertPath, tlsTrustEnvKeys)
	for _, key := range tlsTrustEnvKeys {
		if err := os.Setenv(key, caCertPath); err != nil {
			return fmt.Errorf("failed to set %s: %w", key, err)
		}
	}
	logTLS.Printf("TLS trust environment configured successfully: %d env vars set", len(tlsTrustEnvKeys))
	return nil
}

// LoadGatewayTLS loads a TLS configuration for the gateway HTTP server from PEM
// certificate and key files. When caPath is non-empty the returned config
// requires client certificates signed by that CA (mutual TLS / mTLS).
//
// Pass an empty caPath to use one-way TLS (server-only authentication).
//
// Example — one-way TLS (server cert only):
//
//	tlsCfg, err := LoadGatewayTLS("/path/server.crt", "/path/server.key", "")
//
// Example — mutual TLS (client certs required):
//
//	tlsCfg, err := LoadGatewayTLS("/path/server.crt", "/path/server.key", "/path/ca.crt")
func LoadGatewayTLS(certPath, keyPath, caPath string) (*tls.Config, error) {
	logTLS.Printf("loading gateway TLS: cert=%s, key=%s, ca=%s", certPath, keyPath, caPath)

	serverCert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		return nil, fmt.Errorf("failed to load server TLS certificate/key: %w", err)
	}
	logTLS.Printf("server TLS key pair loaded: certChainLen=%d", len(serverCert.Certificate))

	cfg := NewServerTLSConfig(serverCert)

	if caPath != "" {
		caPEM, err := os.ReadFile(caPath)
		if err != nil {
			return nil, fmt.Errorf("failed to read CA certificate: %w", err)
		}

		caPool := x509.NewCertPool()
		if !caPool.AppendCertsFromPEM(caPEM) {
			return nil, fmt.Errorf("failed to parse CA certificate from %s", caPath)
		}
		logTLS.Printf("CA certificate pool built: ca=%s", caPath)

		// Require and verify client certificates signed by the provided CA.
		cfg.ClientCAs = caPool
		cfg.ClientAuth = tls.RequireAndVerifyClientCert
		logTLS.Printf("mTLS enabled: client certificates required, CA=%s", caPath)
	} else {
		logTLS.Print("one-way TLS configured: client certificates not required")
	}

	logTLS.Printf("gateway TLS configuration ready: minVersion=%s, mtls=%v", tls.VersionName(cfg.MinVersion), caPath != "")
	return cfg, nil
}
