// Package httputil — generic HTTP helper utilities.
//
// TLS helpers are split across two packages:
//
//   - internal/httputil (this package): protocol-level helpers that apply to
//     all TLS listeners and clients (MinTLSVersion, NewServerTLSConfig,
//     NewClientTLSConfig, ConfigureTLSTrustEnvironment).
//
//   - internal/proxy: certificate *generation* (GenerateSelfSignedTLS) lives
//     there because it is only needed when the proxy runs in self-signed mode.
//     It calls httputil.NewServerTLSConfig to assemble the final *tls.Config.
package httputil

import (
	"crypto/tls"
	"fmt"
	"os"
	"strings"

	"github.com/github/gh-aw-mcpg/internal/logger"
)

var logTLS = logger.New("httputil:tls")

// MinTLSVersion is the minimum TLS version enforced across all gateway listeners
// and clients. Centralizing this constant ensures a single point of change if
// the policy is tightened (e.g., to tls.VersionTLS13).
const MinTLSVersion = tls.VersionTLS12

// tlsTrustEnvKeys is the canonical set of well-known environment variables
// that point HTTP/TLS clients (Node.js, curl, git, Python requests) to a CA
// bundle.
var tlsTrustEnvKeys = []string{
	"NODE_EXTRA_CA_CERTS",
	"SSL_CERT_FILE",
	"GIT_SSL_CAINFO",
	"CURL_CA_BUNDLE",
	"REQUESTS_CA_BUNDLE",
}

// TLSTrustEnvKeys returns the set of trust-environment variable names used by
// ConfigureTLSTrustEnvironment.
//
// The returned slice is a defensive copy and can be safely modified by callers
// without affecting package behavior.
func TLSTrustEnvKeys() []string {
	return append([]string(nil), tlsTrustEnvKeys...)
}

// NewServerTLSConfig returns a *tls.Config for TLS server listeners carrying
// the provided certificate and the gateway-wide minimum TLS version.
func NewServerTLSConfig(cert tls.Certificate) *tls.Config {
	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   MinTLSVersion,
	}
}

// NewClientTLSConfig returns a *tls.Config suitable for outbound HTTP clients,
// enforcing the gateway-wide minimum TLS version.
func NewClientTLSConfig() *tls.Config {
	return &tls.Config{MinVersion: MinTLSVersion}
}

// ConfigureTLSTrustEnvironment sets all trust-environment variables to
// caCertPath so that
// child processes (Node.js, curl, git, Python) automatically trust the
// self-signed CA certificate generated by internal/proxy.GenerateSelfSignedTLS.
func ConfigureTLSTrustEnvironment(caCertPath string) error {
	if strings.ContainsAny(caCertPath, "\r\n") {
		return fmt.Errorf("invalid TLS CA cert path contains newline")
	}

	logTLS.Printf("Configuring TLS trust environment: caCertPath=%s, envVars=%v", caCertPath, tlsTrustEnvKeys)
	for _, key := range tlsTrustEnvKeys {
		if err := os.Setenv(key, caCertPath); err != nil {
			return fmt.Errorf("failed to set %s: %w", key, err)
		}
	}
	logTLS.Printf("TLS trust environment configured successfully: %d env vars set", len(tlsTrustEnvKeys))
	return nil
}
